-- Create database fileFlipperDB with tables
CREATE DATABASE fileFlipperDB;
-- switch search path to new created DB
SET search_path TO fileFlipperDB;
-- Create tables
-- CREATE user fileAdmin
create role fileAdmin with login password 'test1234';
-- Grant user fileAdmin all privileges on database fileFlipperDB
GRANT CONNECT ON DATABASE fileFlipperDB TO fileAdmin;
-- Grant user CRUD access
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO fileAdmin;